# Generated by Django 6.0.4 on 2026-05-08 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_categoria_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
